import setuptools

setuptools.setup(
      name='cohere_ui',
      author='Barbara Frosik, Ross Harder',
      author_email='bfrosik@anl.gov',
      url='https://github.com/advancedPhotonSource/cohere/cohere-ui',
      version='4.2.1',
      packages=['cohere_ui', 
                'cohere_ui.api', 
                'cohere_ui.beamlines.aps_1ide', 
                'cohere_ui.beamlines.aps_34idc', 
                'cohere_ui.beamlines.esrf_id01', 
                'cohere_ui.beamlines.Petra3_P10', 
                'cohere_ui.beamlines.simple'],
      entry_points={'console_scripts': ['beamline_preprocess=cohere_ui.beamline_preprocess:main',
                                        'beamline_visualization=cohere_ui.beamlines.visualization:main',
                                        'cohere_gui=cohere_ui.cohere_gui:main',
                                        'copy_setup=cohere_ui.copy_setup:main',
                                        'create_aps34idc_experiment=cohere_ui.create_aps34idc_experiment:main',
                                        'everything=cohere_ui.everything:main',
                                        'run_reconstruction=cohere_ui.run_reconstruction:main',
                                        'simple_phasing=cohere_ui.simple_phasing:main',
                                        'standard_preprocess=cohere_ui.standard_preprocess:main']},
      install_requires=[
                         'pyqt5',
                         'scikit-image',
                         'xrayutilities',
                         'pyvista',
                         'scipy==1.14.1',
                         'notebook',
                         'gputil',
                        ],
      classifiers=[
            'Intended Audience :: Science/Research',
            'Programming Language :: Python :: 3.10',
            'Programming Language :: Python :: 3.11',
      ],
)
